In [1]:
import torch
import pandas as pd 
import numpy as np

from matplotlib import pyplot as plt

## Introduction to Tensors
# Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7) # Create a Scalar
scalar.item() # Get the Python int from PyTorch Scalar

7

In [3]:
# Vector
vector = torch.tensor([5, 6, 7])
vector

tensor([5, 6, 7])

In [4]:
# Matrix
matrix = torch.tensor([[7, 7],
                              [4, 3]])
matrix

tensor([[7, 7],
        [4, 3]])

In [5]:
# Tensor
tensor = torch.tensor([[[1, 2, 3], 
                        [4, 5, 6],
                        [7, 8, 9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## Random Tensor

In [6]:
# Create a Random Tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5888, 0.4612, 0.6420, 0.3686],
        [0.7693, 0.5800, 0.0486, 0.8621],
        [0.7844, 0.2326, 0.9111, 0.2839]])

In [7]:
# Create a random tensor with similar shape to an image
random_image_tensor = torch.rand(250, 250, 3) # height, widgth, colour channel -> (R, G, B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([250, 250, 3]), 3)

## Zeros and Ones

In [8]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# Create a tensor of all Ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a Range of Tensors and Tensors-Like

In [10]:
# Use a torch.range()

zero_to_nine = torch.arange(start=0, end=10)
range_with_step = torch.arange(0, 1000, 50)

range_with_step

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [11]:
# Creating a tensors like
ten_zeros = torch.zeros_like(input=zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

 ## Getting Information from Tensors

 1. Tensors Datatype -> to do get datatype from a tensor, can use `tensor.dtype`
 2. Tensors Shape -> to do get shape from tensor, can use `tensor.shape`
 3. Tensors Device -> to do get device info from tensor, can use `tensor.device`

In [12]:
# Create a tensor
example_tensor = torch.rand(size=(5, 6), device='cpu')
example_tensor

tensor([[7.1828e-01, 8.2557e-01, 2.4301e-02, 1.7273e-04, 2.9080e-01, 5.0330e-01],
        [6.7093e-01, 1.5533e-01, 1.0489e-01, 1.1800e-01, 4.9550e-01, 1.8638e-01],
        [3.9255e-01, 1.1996e-01, 4.5158e-01, 5.6822e-01, 9.7941e-02, 4.3108e-01],
        [5.7313e-01, 6.1284e-02, 4.3623e-01, 4.4748e-01, 2.5095e-01, 7.4486e-02],
        [1.2791e-01, 7.4426e-01, 6.4227e-01, 8.3511e-01, 5.3315e-01, 9.1653e-01]])

In [13]:
# Find out details about some tensor
print(f'Datatype of tensor: {example_tensor.dtype}')
print(f'Shape of tensor: {example_tensor.shape}')
print(f'Device info of tensor: {example_tensor.device}')

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([5, 6])
Device info of tensor: cpu


## Manipulating Tensors (tensor operatiıns)

Tensor Operations include:
  * Addition
  * Subtraction
  * Multiplication
  * Division
  * Matrix Multiplication

In [14]:
# Tensor Operation - Addition 

# Create a random tensor
tensor = torch.rand(3, 4)
print(f'before the addition: {tensor}')
tensor = tensor + 10 # addition the tensor for each element
print(f'after the addition: {tensor}')

before the addition: tensor([[0.2130, 0.5221, 0.1572, 0.2799],
        [0.9152, 0.1798, 0.1632, 0.9341],
        [0.0373, 0.5979, 0.5678, 0.7873]])
after the addition: tensor([[10.2130, 10.5221, 10.1572, 10.2799],
        [10.9152, 10.1798, 10.1632, 10.9341],
        [10.0373, 10.5979, 10.5678, 10.7873]])


In [15]:
# Tensor Operation - Multiplication

# Create a random tensor
tensor = torch.rand(3, 4)
print(f'before the multiplication: {tensor}')
tensor = tensor * 10 # multiply the tensor for each element
print(f'after the multiplication: {tensor}')

before the multiplication: tensor([[0.5370, 0.5945, 0.5963, 0.9733],
        [0.9577, 0.6133, 0.2791, 0.7734],
        [0.9156, 0.9774, 0.6424, 0.1087]])
after the multiplication: tensor([[5.3696, 5.9447, 5.9626, 9.7330],
        [9.5772, 6.1328, 2.7908, 7.7343],
        [9.1559, 9.7744, 6.4242, 1.0868]])


In [16]:
# Tensor Operation - Subtruction

# Create a random tensor
tensor = torch.rand(3, 4)
print(f'before the subtraction: {tensor}')
tensor = tensor - 10 # subtract the tensor for each element
print(f'after the subtraction: {tensor}')

before the subtraction: tensor([[0.6871, 0.2323, 0.5557, 0.4797],
        [0.6837, 0.1680, 0.4544, 0.5710],
        [0.8750, 0.7647, 0.3471, 0.9464]])
after the subtraction: tensor([[-9.3129, -9.7677, -9.4443, -9.5203],
        [-9.3163, -9.8320, -9.5456, -9.4290],
        [-9.1250, -9.2353, -9.6529, -9.0536]])


In [17]:
# Tensor Operation - Division

# Create a random tensor
tensor = torch.rand(3, 4)
print(f'before the division: {tensor}')
tensor = tensor / 10 # division the tensor for each element
print(f'after the division: {tensor}')

before the division: tensor([[0.5719, 0.0687, 0.1269, 0.8702],
        [0.4913, 0.7992, 0.9931, 0.5606],
        [0.9630, 0.5576, 0.2703, 0.8299]])
after the division: tensor([[0.0572, 0.0069, 0.0127, 0.0870],
        [0.0491, 0.0799, 0.0993, 0.0561],
        [0.0963, 0.0558, 0.0270, 0.0830]])


## Matrix Multiplication
  * Element-wise Multiplication
  * Matrix Multiplication - (dot product)

The main two rules for matrix multiplication to remember are:
  1. The ***inner dimensions*** must match:

  * `(3, 2) @ (3, 2)` -> won't work
  * `(2, 3) @ (3, 2)` -> will work
  * `(3, 2) @ (2, 3)` -> will work

  2. The resulting matrix has the shape of the ***outer dimensions***:

  * `(2, 3) @ (3, 2) -> (2, 2)`
  * `(3, 2) @ (2, 3) -> (3, 3)`

Note: `torch.matmul()`, `torch.mm()`, `@` in python is the symbol and functions for matrix multiplication.

In [18]:
# Element-wise Operation

tensor = torch.tensor([1, 2, 3])
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [19]:
# Matrix Multiplication

first_tensor = torch.rand(2, 3)
second_tensor = torch.rand(3, 2)
matrix_mul_result = torch.matmul(first_tensor, second_tensor) # torch.matmul(), torch.mm(), @ -> Matrix Multiplication
print(f'Result: {matrix_mul_result}')

Result: tensor([[0.7945, 0.5036],
        [0.1054, 0.0794]])


In [20]:
## Finding the min, max, mean, sum, etc - (tensor aggregation)
# Create a tensor

tensor = torch.arange(start=0, end=100, step=10)

# Minimum value of tensor -> torch.min(tensor) or tensor.min()
print(f'Min: {torch.min(tensor)}')

# Maximum value of tensor -> torch.max(tensor) or tensor.max()
print(f'Max: {torch.max(tensor)}')

# Mean value of tensor -> but before applying, you should convert it to float32 dtype
# torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()
print(f'Mean: {torch.mean(tensor.type(torch.float32))}')

# Sum of tensor -> torch.sum(tensor) or tensor.sum()
print(f'Sum: {torch.sum(tensor)}')

Min: 0
Max: 90
Mean: 45.0
Sum: 450


In [21]:
# Find the position in tensor that has the minimum value with argmin()
print(f'Index of min value: {tensor.argmin()}')

# Find the position in tensor that has the maximum value with argmax()
print(f'Index of max value: {tensor.argmax()}')

Index of min value: 0
Index of max value: 9


## Reshaping, stacking, squeezing, and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [22]:
# Let's create a tensor
tensor = torch .arange(1., 10.)
print(f'tensor: {tensor}')
print(f'shape of tensor: {tensor.shape}')

tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
shape of tensor: torch.Size([9])


In [23]:
# Reshape - add a extra dimension

tensor_reshape = tensor.reshape(1, 9)
print(f'reshaped tensor: {tensor_reshape}')
print(f'reshaped tensor shape: {tensor_reshape.shape}')

reshaped tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
reshaped tensor shape: torch.Size([1, 9])


In [24]:
# View - change the view
# It's similar to reshape, but view keep the same memory as the original tensor
# Changes to view change the tensor 

view = tensor.view(1, 9)
print(f'view: {view}')
print(f'view of tensor: {view.shape}')

view: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
view of tensor: torch.Size([1, 9])


In [25]:
# Stack - stack tensors on top of each other
# Change the `dim` and see what's happening

tensor_stacked = torch.stack([tensor, tensor, tensor], dim=0)
tensor_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [26]:
# torch.squeeze() - removes all single dimensions from a target tensor

print(f'before applying squeeze - tensor: {tensor_reshape}')
print(f'before applying squeeze - shape: {tensor_reshape.shape}')
squeeze = torch.squeeze(tensor_reshape)
print(f'after applying squeeze - tensor: {squeeze}')
print(f'after applying squeeze - shape: {squeeze.shape}')

before applying squeeze - tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
before applying squeeze - shape: torch.Size([1, 9])
after applying squeeze - tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
after applying squeeze - shape: torch.Size([9])


In [27]:
# torch.unsqueeze() - add a single dimensions to a target tensor

print(f'before applying unsqueeze - tensor: {squeeze}')
print(f'before applying unsqueeze - shape: {squeeze.shape}')
unsqueeze = torch.unsqueeze(squeeze, dim=0)
print(f'after applying unsqueeze - tensor: {unsqueeze}')
print(f'after applying unsqueeze - shape: {unsqueeze.shape}')

before applying unsqueeze - tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
before applying unsqueeze - shape: torch.Size([9])
after applying unsqueeze - tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
after applying unsqueeze - shape: torch.Size([1, 9])


In [28]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order

original_tensor = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
permuted_tensor = torch.permute(original_tensor, (2, 0, 1)) # shifts axis 0->1, 1->2, 2->0

print(f'before applying permute - shape: {original_tensor.shape}')
print(f'after applying permute - shape: {permuted_tensor.shape}')

before applying permute - shape: torch.Size([224, 224, 3])
after applying permute - shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensor)

* Indexing with PyTorch is similar to indexing with NumPy

In [29]:
# Create a tensor
tensor = torch.arange(1, 10).reshape(1, 3, 3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [30]:
# Let's index on our new tensor
tensor[0], tensor[0, 0], tensor[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]), tensor([1, 2, 3]), tensor(1))

## PyTorch tensor & NumPy

In [31]:
import torch
import numpy as np

# NumPy array to PyTorch tensor
# Create a NumPy array
array = np.arange(1., 10.)
tensor = torch.from_numpy(array)

print(f'NumPy Array: {array}')
print(f'PyTorch Tensor: {tensor}')

NumPy Array: [1. 2. 3. 4. 5. 6. 7. 8. 9.]
PyTorch Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


In [32]:
# PyTorch tensor to NumPy array
# Create a tensor
tensor = torch.ones(7)
array = np.array(tensor)

print(f'PyTorch Tensor: {tensor}')
print(f'NumPy Array: {array}')

PyTorch Tensor: tensor([1., 1., 1., 1., 1., 1., 1.])
NumPy Array: [1. 1. 1. 1. 1. 1. 1.]


## Reproducbility (trying to take random out of random)

In [33]:
# Create a random tensor

random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(f'A: {random_tensor_a}')
print(f'B: {random_tensor_b}')
print(f'E: {random_tensor_a == random_tensor_b}')

A: tensor([[0.0320, 0.9874, 0.1640, 0.4601],
        [0.6714, 0.3495, 0.9102, 0.3933],
        [0.0448, 0.0611, 0.4127, 0.6148]])
B: tensor([[0.9439, 0.3798, 0.8769, 0.5964],
        [0.4789, 0.6179, 0.9028, 0.2704],
        [0.2831, 0.9941, 0.2636, 0.9775]])
E: tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [34]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3, 4)

print(f'A: {random_tensor_a}')
print(f'B: {random_tensor_b}')
print(f'E: {random_tensor_a == random_tensor_b}')

A: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
B: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
E: tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##  Running tensors and PyTorch objects on the GPUs

In [35]:
# Find the GPU information
!nvidia-smi

Wed Mar 15 17:24:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   74C    P0    29W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [36]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [37]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [38]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors/models on the GPU

In [39]:
# Create a tensor (default on the CPU)
tensor = torch.rand(3, 4)
print(f'tensor device: {tensor.device}')

tensor device: cpu


In [40]:
# Move tensor to GPU (if avaliable)
tensor_on_cuda = tensor.to(device)
print(f'tensor device: {tensor_on_cuda.device}')

tensor device: cuda:0


## Moving tensors/models back to the CPU

In [41]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_cuda.numpy()

TypeError: ignored

In [42]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_cuda.to('cpu').numpy()
tensor_back_on_cpu

array([[0.86940444, 0.5677153 , 0.74109405, 0.4294045 ],
       [0.8854429 , 0.57390445, 0.26658005, 0.62744915],
       [0.26963168, 0.44136357, 0.29692084, 0.8316855 ]], dtype=float32)